package ru.voidrp.launcher.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public class LauncherManifest {
    // camelCase — as generated by generate_launcher_manifest.py
    @JsonProperty("packName") private String packName = "";
    @JsonProperty("packVersion") private String packVersion = "";
    @JsonProperty("packDisplayVersion") private String packDisplayVersion = "";
    @JsonProperty("launcherProfileId") private String launcherProfileId = "";
    @JsonProperty("neoForgeVersion") private String neoForgeVersion = "";
    @JsonProperty("fmlVersion") private String fmlVersion = "";
    @JsonProperty("neoFormVersion") private String neoFormVersion = "";
    @JsonProperty("buildDateUtc") private String buildDateUtc = "";
    @JsonProperty("minecraftVersion") private String minecraftVersion = "";
    private String loader = "";
    @JsonProperty("javaVersion") private int javaVersion;
    @JsonProperty("minLauncherVersion") private String minLauncherVersion = "";
    @JsonProperty("fullSyncFallback") private boolean fullSyncFallback;
    private String notes = "";
    private ServerInfo server = new ServerInfo();
    private List<ManifestFile> files = new ArrayList<>();

    public String getPackName() { return packName; }
    public void setPackName(String v) { packName = v; }
    public String getPackVersion() { return packVersion; }
    public void setPackVersion(String v) { packVersion = v; }
    public String getPackDisplayVersion() { return packDisplayVersion; }
    public void setPackDisplayVersion(String v) { packDisplayVersion = v; }
    public String getLauncherProfileId() { return launcherProfileId; }
    public void setLauncherProfileId(String v) { launcherProfileId = v; }
    public String getNeoForgeVersion() { return neoForgeVersion; }
    public void setNeoForgeVersion(String v) { neoForgeVersion = v; }
    public String getFmlVersion() { return fmlVersion; }
    public void setFmlVersion(String v) { fmlVersion = v; }
    public String getNeoFormVersion() { return neoFormVersion; }
    public void setNeoFormVersion(String v) { neoFormVersion = v; }
    public String getBuildDateUtc() { return buildDateUtc; }
    public void setBuildDateUtc(String v) { buildDateUtc = v; }
    public String getMinecraftVersion() { return minecraftVersion; }
    public void setMinecraftVersion(String v) { minecraftVersion = v; }
    public String getLoader() { return loader; }
    public void setLoader(String v) { loader = v; }
    public int getJavaVersion() { return javaVersion; }
    public void setJavaVersion(int v) { javaVersion = v; }
    public String getMinLauncherVersion() { return minLauncherVersion; }
    public void setMinLauncherVersion(String v) { minLauncherVersion = v; }
    public boolean isFullSyncFallback() { return fullSyncFallback; }
    public void setFullSyncFallback(boolean v) { fullSyncFallback = v; }
    public String getNotes() { return notes; }
    public void setNotes(String v) { notes = v; }
    public ServerInfo getServer() { return server; }
    public void setServer(ServerInfo v) { server = v != null ? v : new ServerInfo(); }
    public List<ManifestFile> getFiles() { return files; }
    public void setFiles(List<ManifestFile> v) { files = v != null ? v : new ArrayList<>(); }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ServerInfo {
        private String host = "";
        private int port = 25565;

        public String getHost() { return host; }
        public void setHost(String v) { host = v; }
        public int getPort() { return port; }
        public void setPort(int v) { port = v; }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ManifestFile {
        private String path = "";
        private long size;
        private String sha256 = "";
        private String url = "";
        @JsonProperty("alwaysOverwrite") private boolean alwaysOverwrite;
        private boolean optional;
        private boolean required;
        @JsonProperty("displayName") private String displayName = "";
        private String description = "";

        public String getPath() { return path; }
        public void setPath(String v) { path = v; }
        public long getSize() { return size; }
        public void setSize(long v) { size = v; }
        public String getSha256() { return sha256; }
        public void setSha256(String v) { sha256 = v; }
        public String getUrl() { return url; }
        public void setUrl(String v) { url = v; }
        public boolean isAlwaysOverwrite() { return alwaysOverwrite; }
        public void setAlwaysOverwrite(boolean v) { alwaysOverwrite = v; }
        public boolean isOptional() { return optional; }
        public void setOptional(boolean v) { optional = v; }
        public boolean isRequired() { return required; }
        public void setRequired(boolean v) { required = v; }
        public String getDisplayName() { return displayName; }
        public void setDisplayName(String v) { displayName = v; }
        public String getDescription() { return description; }
        public void setDescription(String v) { description = v; }
    }
}
